# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31608b897c38c386a80ec3e0fa35060fdda44d8556e768bc3f075de1de9bf29bae02f248224aa39a0603ec6684ab52424cc917a6c86b6773241d0d546139d1c2

test:
  secret_key_base: db8a84e0d4987b916a18ade5ee02fe579f48304c7aceee71a5dee55116ae5faf8bb7e3414229ea731810f6c1e68ab6106f32a5c80965fead908046685883b233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
