# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8804633b4edfbe9613de1e8139eec1a802568e0799cf677ca2be55f7c3b4f1b307e6675852126d0d512a2d4c93fe7b0c364aff3f0b649c53197f5cdbf48201f7

test:
  secret_key_base: fa93cd75300d6b367e8e7af7d5a45ebfe3e90d7c558e131a4362187355e33df601c0dba8ab8dfe37f288dbadb37d431924775d5e6b0e5dd0eb0d8e684d20d2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
