# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c5509488efd172dc9d40bde787b5485d9c9d28597304eaa440327affbe97fba2650daf8c5da0f4bb2b0f294d6b4610dbae6f7b9e8ee69b096184578771bc395

test:
  secret_key_base: 0d441b3b1ccfcaa479bfa9903b667c7976c7a3b57275b2f8500dec733e9a92b6f7a50411f6709f5d53408c56456fe6b8be776a227e9f52482ad0a34b011a66a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
